### ISSUE TITLE
2006 player?

### ISSUE THREAD

**Issue by xxHAKRxx** [ktg5/PlayerTube#4]
Back when this was GitHub only, I noticed that you teased that the 2006 YT player would come with the extension eventually. Is that still planned or did you abandon that?

**Comment by ktg5** [comment]
The 2006 style was in development when v2.0 for the old userscript was in development. I didn't get to finish it though, due to YouTube's base player script & the YouTube website itself being very complex.
At somepoint I would like to get the 2006 style somewhat working, but for now, it won't really work.

**Comment by ktg5** [comment]
Coming back to this from the recent news I got from #6, this might be more do-able.

**Comment by ktg5** [comment]
Although I think I might just have to turn the Progress Bar into a scrubber and "duplicate" the Progress Bar using the Fake Bar I made to solve issue 6.

**Comment by ktg5** [comment]
forgot to mention that this has been added in v1.6.1, which is currently available on the Actions tab as it's still under some development but working
